name: Build & Test project

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read

jobs:
  assemble:
    name: Assemble
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle assemble
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble
  check:
    name: Check
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle check
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
