name: CD

on: release

permissions:
  contents: read

jobs:
  job:
    name: Release
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle 'build'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Execute Gradle 'publishPlugins'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            publishPlugins 
            -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} 
            -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
